name: quds_ui_kit_rmx
description: Flutter UI kit [(animating icons, buttons, texts, counter, digital clock) - page transitions - toasts - dialogs-  pagination - splash screen ...etc ]
version: 0.0.1
repository: https://github.com/Ins3nsE/QudsUI_rmx

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quds_ui_kit: ^0.0.7+10

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

